export interface Work {
  id: string;
  title: string;
  ageOfPublication: number;
  year: number;
  join: number;
  split: number;
  region: string;
  originalLanguage: string;
  literatureForm: string;
  originCountry: string;
  downloads: number;
  subjects: string;
  language: string;
  size: number;
  wordsCount: number;
  completedFlag: number;
  literaryPeriod: string;
  literaryForm: string;
  rFrameMean: number;
  nFrameMean: number;
  hFrameMean: number;
  sFrameMean: number;
  rWork: number;
  nWork: number;
  hWork: number;
  sWork: number;
  rBeta: number;
  hBeta: number;
  sBeta: number;
  rFrameMeanGenDiv: number;
  rWorkGenDiv: number;
  nFrameMeanGenDiv: number;
  nWorkGenDiv: number;
  rBetaGenDiv: number;
  nBetaGenDiv: number;
  authorId: string
}
